name: sf-stim
channels:
  - conda-forge
  - defaults
dependencies:
  - python==3.7
  - anaconda
  - pip
  - jupyter
  - jupyterlab
  - ipykernel
  - numpy
  - matplotlib
  - scipy
  - seaborn
  - pandas
  - pillow
  - pip:
      - pyrtools>=1.0
